- hosts: localhost
  tasks: 
   - name: Set Global Git config 
     git_config: 
       name: "{{ item.name }}"
       value: "{{ item.value }}"
       scope: global
     with_items:
      - { name: 'user.name', value: 'Damien Nugent' }
      - { name: 'user.email', value: 'damien@damiennugent.com' }
      - { name: 'core.editor', value: 'vim' }

   - name: Create gitstuff directory
     file: 
       state: directory
       path: '{{ ansible_env.HOME }}/gitstuff'

   - name: Pull dotfiles from github
     git:
       repo: 'https://github.com/Tsiklon/dot-files.git' 
       dest: '{{ ansible_env.HOME }}/gitstuff/dot-files'

   - name: link dot files
     file: 
       state: link 
       src: "{{ item.src }}" 
       dest: "{{ item.dest }}"
     with_items:
      - { src: '{{ ansible_env.HOME }}/gitstuff/dot-files/vimrc', dest: '{{ ansible_env.HOME }}/.vimrc'}
      - { src: '{{ ansible_env.HOME }}/gitstuff/dot-files/tmux.conf', dest: '{{ ansible_env.HOME }}/.tmux.conf'}
